# File: .github/workflows/workflow.yml
 
on: [push]
 
name: Run Azure Login With a Service Principal Secret
permissions:
  id-token: write
  contents: read
env:
  resourceGroupName: 'myResourceGroup'
  branch: 'buildtoacr_01082024'
 
jobs:
 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        ref: ${{ env.branch}}
    # - name: Login to Azure Container Registry
    #   uses: Azure/docker-login@v1
    #   with:
    #     # Container registry username
    #     username: ${{ secrets.ACR_USERNAME }}
    #     # Container registry password
    #     password: ${{ secrets.ACR_PASSWORD }}
    #     # Container registry server url
    #     login-server: ${{ secrets.ACRNAME }}.azurecr.io

    # - name: Build the Docker image
    #   run:         
    #     docker build . --file Dockerfile --tag ${{secrets.ACRNAME}}.azurecr.io/swagger-petstore:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
    #     docker tag ${{secrets.ACRNAME}}.azurecr.io/swagger-petstore:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ${{secrets.ACRNAME}}.azurecr.io/swagger-petstore:latest;
    #     docker push ${{secrets.ACRNAME}}.azurecr.io/swagger-petstore:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
    #     docker push ${{secrets.ACRNAME}}.azurecr.io/swagger-petstore:latest;

    # Add id token and contents to the permissions
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        # enable-AzPSSession: true
    # - uses: azure@arm-deploy@v1
    #   with:
    #     scope: 'resource-group'
    #     deployment-name: ${{github.run_id}}
    #     resource-group: 'myResourceGroup'
    #     template: ./infra/main.bicep
    #     deployment-mode: 'Incremental'
    - name: Deploy Azure Container App
      shell: pwsh
      run: |
        ./deploy_infra.ps1