# File: .github/workflows/workflow.yml
 
on: [push]
 
name: Run Azure Login With a Service Principal Secret
 
jobs:
 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    - name: use REPO
      run: |
        echo "The value of REPO is: ${REPO}"
 
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        username: $(az acr credential show -n ${{ secrets.REGISTRY_NAME }} --query username -o tsv)
        password: $(az acr credential show -n ${{ secrets.REGISTRY_NAME }} --query "passwords[0].value" -o tsv)
    - name: List Directory
      run: |
       pwd
       ls -la
    - name: Build docker image
      run: docker build . -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/${REPO}-test:latest
    - name: Push docker image
      run: docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/${REPO}-test:latest
